http:
  port: 3001
  auth:
    basic:
      username: 'user1'
      password: 'pass1'

auth:
  jwt:
    secret: ''
    algorithms: 'ES256' # RS256, ES256, ES384, ES512
    public_key: 'LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUZZd0VBWUhLb1pJemowQ0FRWUZLNEVFQUFvRFFnQUUxK2F0bXU4V3c0eUYyYkt0SE1mV3VuVmIyRVRqd3NnRAppU0FQbGR0bGhORldRNUpmZHUzQTBqclpqMERVWUxRbHNLK1pCTk5DeHM1NzZseTRiQTErOEE9PQotLS0tLUVORCBQVUJMSUMgS0VZLS0tLS0K'
    private_key: 'LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IUUNBUUVFSUNPOWh2YjA2R3d2aE5CSUR5bnRjcHloMWxRVEgvODZNVWMxRFBTdU5XRnBvQWNHQlN1QkJBQUsKb1VRRFFnQUUxK2F0bXU4V3c0eUYyYkt0SE1mV3VuVmIyRVRqd3NnRGlTQVBsZHRsaE5GV1E1SmZkdTNBMGpyWgpqMERVWUxRbHNLK1pCTk5DeHM1NzZseTRiQTErOEE9PQotLS0tLUVORCBFQyBQUklWQVRFIEtFWS0tLS0tCg='
